rm(list=ls())

library(ggplot2)
theme_set(theme_bw())
library(lubridate)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel)
options(ggrepel.max.overlaps = Inf)
library(tools)
library(ozmaps)
library(dplyr)
library(ggspatial)

data <- read.table("data/weatherAUS.csv", header=T, sep=",", na.string="NA", dec=".", quote="")
data$Date <- as.Date(data$Date)
data$Day <- yday(data$Date)
data$Year=format(data$Date, format="%Y")
